import './globals.css';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

const inter = Montserrat({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-[#fcfcfc]`}>{children}</body>
    </html>
  );
}
